// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kluukkmikpkybcbbaotq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtsdXVra21pa3BreWJjYmJhb3RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MjAwNDcsImV4cCI6MjA2NjI5NjA0N30.IxfC71a_jqQzQfdnHVo6wHj9oY7WAIioJbyT6LI77m8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});